# Generated by Django 5.2.11 on 2026-02-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Туман')),
            ],
            options={
                'verbose_name': 'Туман',
                'verbose_name_plural': 'Туманлар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фермер номи')),
                ('inn', models.CharField(max_length=20, unique=True, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаол')),
            ],
            options={
                'verbose_name': 'Фермер',
                'verbose_name_plural': 'Фермерлар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Маҳсулот номи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаол')),
            ],
            options={
                'verbose_name': 'Маҳсулот',
                'verbose_name_plural': 'Маҳсулотлар',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Вилоят')),
            ],
            options={
                'verbose_name': 'Вилоят',
                'verbose_name_plural': 'Вилоятлар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номи')),
                ('type', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], verbose_name='Типи')),
                ('coefficient', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Селекцион нав',
                'verbose_name_plural': 'Селекцион навлар',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Номи')),
                ('short_name', models.CharField(max_length=20, verbose_name='Қисқартма')),
            ],
            options={
                'verbose_name': 'Ўлчов бирлиги',
                'verbose_name_plural': 'Ўлчов бирликлари',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Шартнома рақами')),
                ('date', models.DateField(verbose_name='Шартнома санаси')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Режадаги миқдор (тонна)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='1 тонна нархи')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Жами сумма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаол')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='query.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Шартнома',
                'verbose_name_plural': 'Шартномалар',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Банк номи')),
                ('account_number', models.CharField(max_length=50, verbose_name='Ҳисоб рақами')),
                ('mfo', models.CharField(max_length=10, verbose_name='МФО')),
                ('is_main', models.BooleanField(default=False, verbose_name='Асосий ҳисоб')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='query.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Банк ҳисоб рақами',
                'verbose_name_plural': 'Банк ҳисоб рақамлари',
            },
        ),
        migrations.CreateModel(
            name='GoodsGivenDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Ҳужжат рақами')),
                ('date', models.DateField(verbose_name='Сана')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.contract', verbose_name='Шартнома')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Товар бериш ҳужжати',
                'verbose_name_plural': 'Товар бериш ҳужжатлари',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Ҳужжат рақами')),
                ('date', models.DateField(verbose_name='Сана')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.contract', verbose_name='Шартнома')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Пахта қабул ҳужжати',
                'verbose_name_plural': 'Пахта қабул ҳужжатлари',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Сана')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Кредит')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='query.contract', verbose_name='Шартнома')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='query.goodsgivendocument', verbose_name='Ҳужжат')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='query.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Ҳаракат журнали',
                'verbose_name_plural': 'Ҳаракат журнали',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Massive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Массив')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massives', to='query.district', verbose_name='Туман')),
            ],
            options={
                'verbose_name': 'Массив',
                'verbose_name_plural': 'Массивлар',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='farmer',
            name='massive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.massive', verbose_name='Массив'),
        ),
        migrations.CreateModel(
            name='GoodsGivenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Миқдори')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Нарх')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма')),
                ('vat_rate', models.CharField(choices=[('0', 'Без НДС'), ('12', '12%'), ('15', '15%')], default='12', max_length=5, verbose_name='НДС ставкаси')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='НДС суммаси')),
                ('total_with_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Жами сумма')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_given', to='query.goodsgivendocument', verbose_name='Ҳужжат')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.product', verbose_name='Маҳсулот')),
            ],
            options={
                'verbose_name': 'Товар бериш',
                'verbose_name_plural': 'Товар беришлар',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='query.region', verbose_name='Вилоят'),
        ),
        migrations.CreateModel(
            name='SortClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Сорт')),
                ('class_grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Класс')),
                ('coefficient', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Сорт/Класс',
                'verbose_name_plural': 'Сорт/Класслар',
                'unique_together': {('sort', 'class_grade')},
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Сана')),
                ('physical_weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Физик вазн')),
                ('impurity', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Ифлослик %')),
                ('calculated_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ҳисобий вазн')),
                ('moisture', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Намлик %')),
                ('conditional_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кондицион вазн')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Нарх')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Сумма')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_received_items', to='query.goodsgivendocument', verbose_name='Ҳужжат')),
                ('selection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.selectiontype', verbose_name='Селекцион нав')),
                ('sort_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.sortclass', verbose_name='Сорт / Класс')),
            ],
            options={
                'verbose_name': 'Қабул қилинган пахта',
                'verbose_name_plural': 'Қабул қилинган пахталар',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.unit', verbose_name='Ўлчов бирлиги'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('farmer', 'number'), name='unique_contract_per_farmer'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('farmer',), name='unique_main_account_per_farmer'),
        ),
        migrations.AlterUniqueTogether(
            name='massive',
            unique_together={('district', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
    ]
