# Generated by Django 5.2.11 on 2026-02-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsgivenitem',
            options={'verbose_name': 'Товар бериш позицияси', 'verbose_name_plural': 'Товар бериш позициялари'},
        ),
        migrations.AlterField(
            model_name='goodsgivenitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='query.goodsgivendocument', verbose_name='Товар бериш ҳужжати'),
        ),
        migrations.AlterField(
            model_name='goodsgivenitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query.product', verbose_name='Маҳсулот'),
        ),
    ]
