# Generated by Django 5.2.11 on 2026-02-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_alter_goodsgivenitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiveditem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='query.goodsreceiveddocument', verbose_name='Пахта қабул ҳужжати'),
        ),
    ]
