# Generated by Django 5.2.11 on 2026-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_alter_goodsreceiveditem_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectiontype',
            name='coefficient',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Коэффициент'),
        ),
    ]
