# Generated by Django 5.2.11 on 2026-02-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_alter_selectiontype_coefficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiveditem',
            name='date',
        ),
    ]
