# Generated by Django 5.2.11 on 2026-02-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_remove_goodsreceiveditem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='document',
        ),
        migrations.AddField(
            model_name='ledger',
            name='given_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.goodsgivendocument'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='received_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.goodsreceiveddocument'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.contract'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.farmer'),
        ),
    ]
