# Generated by Django 5.2.11 on 2026-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_remove_ledger_document_ledger_given_document_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='goodsgivendocument',
            constraint=models.UniqueConstraint(fields=('farmer', 'number'), name='unique_given_number_per_farmer'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiveddocument',
            constraint=models.UniqueConstraint(fields=('farmer', 'number'), name='unique_received_number_per_farmer'),
        ),
    ]
