# Generated by Django 5.2.11 on 2026-02-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_goodsgivendocument_unique_given_number_per_farmer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаол')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot фойдаланувчи',
                'verbose_name_plural': 'Bot фойдаланувчилар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='ledger',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='query.contract'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='query.farmer'),
        ),
    ]
