# Generated by Django 5.2.11 on 2026-02-18 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0008_botuser_alter_ledger_contract_alter_ledger_farmer"),
    ]

    operations = [
        migrations.CreateModel(
            name="MineralWarehouseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Сана")),
                (
                    "invoice_number",
                    models.CharField(max_length=50, verbose_name="Накладной рақами"),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("truck", "Юк машинаси"),
                            ("tractor", "Трактор"),
                            ("train", "Поезд"),
                            ("other", "Бошқа"),
                        ],
                        max_length=20,
                        verbose_name="Транспорт русуми",
                    ),
                ),
                (
                    "transport_number",
                    models.CharField(max_length=30, verbose_name="Транспорт рақами"),
                ),
                (
                    "bag_count",
                    models.PositiveIntegerField(default=0, verbose_name="Қоп сони"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Миқдори"
                    ),
                ),
                (
                    "warehouse_name",
                    models.CharField(max_length=255, verbose_name="Омбор номи"),
                ),
            ],
            options={
                "verbose_name": "Омбор кирим ҳужжати",
                "verbose_name_plural": "Омбор кирим ҳужжатлари",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="goodsgivendocument",
            name="warehouse_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="given_documents",
                to="query.mineralwarehousereceipt",
                verbose_name="Омбор",
            ),
        ),
    ]
