# Generated by Django 5.2.11 on 2026-02-18 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0009_mineralwarehousereceipt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Омбор номи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Омбор",
                "verbose_name_plural": "Омборлар",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="mineralwarehousereceipt",
            name="warehouse_name",
        ),
        migrations.AddField(
            model_name="mineralwarehousereceipt",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="Сумма"
            ),
        ),
        migrations.AddField(
            model_name="mineralwarehousereceipt",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="Нарх"
            ),
        ),
        migrations.AddField(
            model_name="mineralwarehousereceipt",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="query.product",
                verbose_name="Маҳсулот",
            ),
        ),
        migrations.AddField(
            model_name="mineralwarehousereceipt",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="query.warehouse",
                verbose_name="Омбор",
            ),
        ),
    ]
