# Generated by Django 5.2.11 on 2026-02-18 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0010_warehouse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsgivendocument",
            name="warehouse_receipt",
        ),
        migrations.AddField(
            model_name="goodsgivendocument",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="given_documents",
                to="query.warehouse",
                verbose_name="Омбор",
            ),
        ),
    ]
