# Generated by Django 5.2.11 on 2026-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0011_remove_goodsgivendocument_warehouse_receipt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="phone",
        ),
        migrations.AddField(
            model_name="farmer",
            name="maydon",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Майдон",
            ),
        ),
    ]
